#!/usr/bin/env bash
#Displays "Best school" 10 times using while loop
#on 9th iteration, displays "Hi" before "Best school".

count = 0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best school"
	(( count++ ))
done
