#!/usr/bin/env bash
#Loops from 1 to 10, displays:
#"Bad luck" for the 4th iteration
#"Good luck" foe the 8th iteration
#"Best school" for all other iterations

count = 0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	(( count++ ))
done
